# 2023-02-17

name: Example workflow for Python-3.8 using Snyk
on:
  push:
    branches:
      - snyk-01
      # - nonexistent  # avoid triggering
jobs:
  security:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    steps:
      # - uses: actions/checkout@master
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          set -ux
          pwd
          ls -al
          python3 -m venv zvenv
          source zvenv/bin/activate
          pip install pip -U
          # pip install -r aws-dynamodb-encryption-python/requirements.txt
          # pip freeze
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        working-directory: aws-dynamodb-encryption-python
        if:  ${{ '0' == '0' }}

# TODO: command line:
#/usr/bin/docker run --name snyksnykpython38_1a20d7 --label 49859c
# --workdir /github/workspace --rm -e "SNYK_TOKEN" -e "INPUT_COMMAND" -e "INPUT_ARGS" -e "INPUT_JSON"
# -e "FORCE_COLOR" -e "SNYK_INTEGRATION_NAME" -e "SNYK_INTEGRATION_VERSION" -e "HOME" -e "GITHUB_JOB"
# -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID"
# -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID"
# -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF"
# -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL"
# -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA"
# -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF"
# -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS"
# -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL"
# -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true
# -v "/var/run/docker.sock":"/var/run/docker.sock"
# -v "/home/runner/work/_temp/_github_home":"/github/home"
# -v "/home/runner/work/_temp/_github_workflow":"/github/workflow"
# -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands"
# -v "/home/runner/work/sv-security-scans-05a/sv-security-scans-05a":"/github/workspace"
# snyk/snyk:python-3.8  "snyk" "test" ""